version: '3.7'

services:
  app:
    container_name: nestjs-scs-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: scs
    networks:
      - pgnetwork

networks:
  pgnetwork:
    external: true