@startuml
actor Client

participant "AuthService" as Auth
database "Database" as DB

Client -> Auth : [A-01] 이메일과 함께 인증 코드 전송 요청
Auth -> DB : 이메일과 인증 코드 저장
DB -> Auth : 저장 완료
Auth -> Client : 인증 코드 전송 완료

Client -> Auth : [A-02] 이메일과 인증 코드 검증 요청
Auth -> DB : 이메일과 인증 코드 검증
DB -> Auth : 검증 결과
Auth -> Client : 인증 코드 검증 결과

Client -> Auth : [A-03] 개인 정보와 인증 코드 포함 회원 가입 요청
Auth -> DB : 이메일과 인증 코드 검증
DB -> Auth : 검증 결과
Auth -> DB : 회원 정보 저장
DB -> Auth : 저장 완료
Auth -> Client : 회원 가입 완료
@enduml
